#!/bin/sh
VIMHOME=~/.vim/vim-init
VIMFILE=~/.vimrc
PWD=$(cd $(dirname $0); pwd)

param=$1
pathFile='vimrc.path'

# function
warn() {
  echo "WARNING: $1" >&2
}
error() {
  echo "ERROR: $1" >&2
  exit 1
}
#echo "Installing hightman/vimrc from: $PWD ..."
echo "Installing wangcan/vimrc-plug from: $PWD ..."

# backup exists file/dir
if [ $param == 'first' ]; then
  echo "Checking to backup old configurations ..."
  #for f in $VIMHOME $VIMFILE; do
    #if [ -e "$f" ]; then
      #if [ -e "${f}_bak" ]; then
        #rm -rf ${f}_bak || error "Can't remove exists backup file: ${f}_bak"
      #fi
      #mv $f ${f}_bak || error "Can't rename exists file: $f"  
    #fi
  #done
  echo "Create symbol links ..."
  ln -sf $PWD $VIMHOME
  ln -sf $PWD/vimrc $VIMFILE

  echo "Initlize bundles ..."
  cd $PWD
  #mkdir tmp bak -p

  #echo '" Path of Utils' > $pathFile
  #echo '" Notice: This file generated by install script automatically' >> $pathFile
fi

#git submodule update --init
#vim +BundleInstall! +BundleClean +q +q

echo "VIMRC installed, Enjoy it :-)"

